// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';

export function CreateTask(arg1:task.Request):Promise<task.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function FilterTasksByPriority(arg1:task.Priority):Promise<Array<task.Task>>;

export function FilterTasksByStatus(arg1:task.Status):Promise<Array<task.Task>>;

export function ListTasks():Promise<Array<task.Task>>;

export function UpdateTask(arg1:string,arg2:task.Request):Promise<void>;
