// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['app']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function FilterTasksByPriority(arg1) {
  return window['go']['app']['App']['FilterTasksByPriority'](arg1);
}

export function FilterTasksByStatus(arg1) {
  return window['go']['app']['App']['FilterTasksByStatus'](arg1);
}

export function ListTasks() {
  return window['go']['app']['App']['ListTasks']();
}

export function UpdateTask(arg1, arg2) {
  return window['go']['app']['App']['UpdateTask'](arg1, arg2);
}
